project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - prepare/install-tools.qmd
    - understand/index.qmd
    - understand/observed-size-spectra.qmd
    - understand/single-species-spectra.qmd
    - understand/predation-growth-and-mortality.qmd
    - understand/species-interactions.qmd
    - understand/dynamics-of-spectra.qmd
    - build/index.qmd
    - build/collect-parameters.qmd
    - build/create-first-model.qmd
    - build/refine.qmd
    - build/landings.qmd
    - build/tune-resilience.qmd
    - use/*

format:
  html:
    theme:
      light: cerulean
      dark: darkly
    css: styles.css
    html-math-method: katex
    code-fold: false
    code-link: true
    code-copy: true
    code-block-bg: true
    code-block-border-left: "#31BAE9"
    anchor-sections: true
    link-external-newwindow: true
    df-print: paged

website:
  title: "mizer course"
  site-url: "https://mizer.course.sizespectrum.org"
  favicon: images/favicon-16x16.png
  repo-url: https://github.com/gustavdelius/mizerCourse
  repo-branch: master
  repo-actions: [edit, issue]
  twitter-card:
    site: "@mizer_model"
    creator: "gustavdelius"
  open-graph: true
  comments:
    giscus:
      repo: gustavdelius/mizerCourse
      category: Comments
      reactions-enabled: false
      input-position: bottom
      repo-id: R_kgDOK0vNNg
      category-id: DIC_kwDOK0vNNs4CbfmH
      loading: lazy
      mapping: title
  search:
    location: navbar
    type: textbox
  navbar:
    title: mizer
    logo-href: https://sizespectrum.org/mizer
    search: true
    left:
      - text: Get started
        href: https://sizespectrum.org/mizer/articles/mizer.html
      - text: Articles
        menu:
          - text: Model types
          - text: The General Mizer Size-spectrum Model
            href: https://sizespectrum.org/mizer/articles/model_description.html
          - text: The Single-Species Model
            href: https://sizespectrum.org/mizer/articles/single_species_size-spectrum_dynamics.html
          - text: The Community Model
            href: https://sizespectrum.org/mizer/articles/community_model.html
          - text: The Trait-Based Model
            href: https://sizespectrum.org/mizer/articles/trait_model.html
          - text: The Multi Species Model
            href: https://sizespectrum.org/mizer/articles/multispecies_model.html
          - text: Tutorials
          - text: Running a Simulation
            href: https://sizespectrum.org/mizer/articles/running_a_simulation.html
          - text: Exploring the Simulation Results
            href: https://sizespectrum.org/mizer/articles/exploring_the_simulation_results.html
          - text: A Multi-Species Model of the North Sea
            href: https://sizespectrum.org/mizer/articles/a_multispecies_model_of_the_north_sea.html
          - text: 'Cheatsheet: Analysis and Plotting'
            href: https://sizespectrum.org/mizer/articles/cheatsheet-analysis-and-plotting.html
          - text: Extending mizer
          - text: Extending mizer
            href: https://sizespectrum.org/mizer/articles/extending-mizer.html
          - text: Using mizer extension packages
            href: https://sizespectrum.org/mizer/articles/using-extension-packages.html
          - text: Creating a mizer extension package
            href: https://sizespectrum.org/mizer/articles/creating-extension-packages.html
          - text: Technical articles
          - text: Incorporating predation diffusion
            href: https://sizespectrum.org/mizer/articles/predation_diffusion.html
          - text: Cohort dynamics and diffusion
            href: https://sizespectrum.org/mizer/articles/cohort_dynamics_and_diffusion.html
          - text: The Numerical Scheme used in Mizer
            href: https://sizespectrum.org/mizer/articles/numerical_details.html
          - text: Fast Fourier Transform for Rates
            href: https://sizespectrum.org/mizer/articles/fft.html
          - text: Analytic Test
            href: https://sizespectrum.org/mizer/articles/analytic_test.html
          - text: More articles...
            href: https://sizespectrum.org/mizer/articles/index.html
      - text: Reference
        href: https://sizespectrum.org/mizer/reference/index.html
      - text: Course
        href: https://mizer.course.sizespectrum.org
      - text: Changelog
        href: https://sizespectrum.org/mizer/news/index.html
      - text: Publications
        href: https://sizespectrum.org/mizer/articles/publications.html
    right:
      - icon: robot
        text: Ask AI
        href: https://notebooklm.google.com/notebook/6aa51f75-d1a8-4140-9180-84532ef5f821
      - text: Blog
        href: https://blog.mizer.sizespectrum.org
      - icon: twitter
        href: https://twitter.com/mizer_model
        aria-label: Twitter
      - icon: github
        href: https://github.com/sizespectrum/mizer/
        aria-label: GitHub
  page-navigation: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: Introduction
        href: index.qmd
      - text: Install tools
        href: prepare/install-tools.qmd
      - section: "Part 1: Understand"
        contents:
        - text: Introduction
          href: understand/index.qmd
        - text: Observed size spectra
          href: understand/observed-size-spectra.qmd
        - text: Single species spectra
          href: understand/single-species-spectra.qmd
        - text: Predation, growth and mortality
          href: understand/predation-growth-and-mortality.qmd
        - text: Species interactions
          href: understand/species-interactions.qmd
        - text: Dynamics of size spectra
          href: understand/dynamics-of-spectra.qmd
      - section: "Part 2: Build"
        contents:
        - text: Introduction
          href: build/index.qmd
        - text: Collect parameters
          href: build/collect-parameters.qmd
        - text: Create your first model
          href: build/create-first-model.qmd
        - text: Refine your model
          href: build/refine.qmd
        - text: Match landings data
          href: build/landings.qmd
        - text: Tune resilience
          href: build/tune-resilience.qmd
      - section: "Part 3: Use"
        contents:
        - text: Introduction
          href: use/index.qmd
        - text: Explore fishing scenarios
          href: use/fishing-scenarios.qmd
        - text: Change resource
          href: use/change-resources.qmd
        - text: Explore further scenarios
          href: use/further-scenarios.qmd
